### ISSUE TITLE
Update for Mac instructions

### ISSUE THREAD

**Issue by philip-peterson** [sdroege/arduino-due-rust#1]
It seems to work on Mac with latest BOSSA (1.9.1-14-g3532de8). You just need to run:

```
sudo bossac -p /dev/cu.usbmodem143201 -e -w -v -b -R image.bin
```

Note the `sudo` and the `-p` parameter.

**Comment by philip-peterson** [comment]
Strike that, it seems to render the device not operable (i.e. doesn't respond to BOSSA device type queries)

**Comment by sdroege** [comment]
Ah, I saw that BOSSA supposedly got a fix for the bug I encountered but I didn't check if that's actually the case. So if I understand you correctly, the latest version doesn't work either?

**Comment by philip-peterson** [comment]
Not sure if it's that same bug that's an issue or if it's a new bug, but at any rate, yeah, writing to an Arduino Due seems to soft-brick the device. It can be reset by writing a program from Arduino IDE.

**Comment by sdroege** [comment]
Sounds like the same bug that I got on Linux with the old BOSSA version, yes.
