### ISSUE TITLE
Serial communication

### ISSUE THREAD

**Issue by MendyBerger** [sdroege/arduino-due-rust#2]
This is a weird one, and a lot to ask, but still, I'm trying my luck...

I'm relatively new to Arduino and microcontrollers but I've been writing Rust code for some time, this repo helped me get up and running with writing to GPIO pins, and I'm really grateful for that! Thanks!!

  However, I'm still having trouble figuring out how serial would work, I can't get a character across the wire, and it's driving me nuts. Any chance you happen to know how to get Serial to work?

**Comment by sdroege** [comment]
I don't know, sorry :) You'll have more luck asking this in an Arduino specific forum/mailing list.
